name: Deploy Flask API

on:
  push:
    branches:
      - main  # Déclencher le déploiement sur chaque push sur la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Preload Machine Learning Model
      run: |
        python - << END
        import tensorflow as tf

        # Charger le modèle de machine learning
        lstm_model = tf.keras.models.load_model('./models/LSTM_plus_Lemmatization_plus_FastText_model.h5')
        print("Modèle de machine learning préchargé.")
        END

    - name: Preload spaCy Model
      run: |
        python - << END
        import spacy

        # Initialiser spaCy
        nlp = spacy.load('en_core_web_sm')
        print("Modèle spaCy préchargé.")
        END

    - name: Preload FastText Model
      run: |
        python - << END
        import gensim.downloader as api

        # Charger le modèle FastText
        ft_model = api.load('fasttext-wiki-news-subwords-300')
        print("Modèle FastText préchargé.")
        END

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tweet-api'
        publish-profile: ${{ secrets.AZURE_API }}
        package: .
