name: Deploy Flask API

on:
  push:
    branches:
      - main  # Déclencher le déploiement sur chaque push sur la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

   - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tweet-api'
        publish-profile: ${{ secrets.AZURE_API }}
        package: .

    - name: Start Gunicorn server
      run: |
        gunicorn --bind 0.0.0.0:$PORT main:app


