name: main_tweet_api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le code source
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Configurer Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # Étape 3 : Mettre à jour pip et installer les dépendances sans environnement virtuel
    - name: Install primary dependencies
      run: |
        python -m pip install --upgrade pip  # Mettre à jour pip
        pip install -r requirements.txt  # Installer les dépendances depuis requirements.txt

    # Étape 4 : Télécharger le modèle FastText (si nécessaire)
    - name: Download FastText model
      run: |
        wget -P ./modèle https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.fr.300.bin.gz
        gunzip ./modèle/cc.fr.300.bin.gz  # Décompresser le modèle FastText

    # Étape 5 : Déployer sur Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tweet-api'
        publish-profile: ${{ secrets.AZURE_API }}
