name: Deploy Flask API

on:
  push:
    branches:
      - main  # Déclencher le déploiement sur chaque push sur la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2: Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # Étape 3: Rendre le script startup.sh exécutable
    - name: Make startup.sh executable
      run: chmod +x ./startup.sh



    # Étape 5: Déployer l'application sur Azure
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tweet-api'  # Nom de votre application sur Azure
        publish-profile: ${{ secrets.AZURE_API }}  # Secret pour l'authentification
        package: .

  # Exécuter le script startup.sh après le déploiement
    - name: Run startup.sh
      run: ./startup.sh






