name: main_tweet_api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install primary dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        
    # Installer FastText en dehors de `requirements.txt`
    - name: Install FastText separately
      run: |
        pip install fasttext==0.9.2  # Installation de FastText séparément

    - name: List installed packages
      run: |
        pip list  # Liste des packages pour vérifier si tout est bien installé

    - name: Download FastText model
      run: |
        wget -P ./modèle https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.fr.300.bin.gz
        gunzip ./modèle/cc.fr.300.bin.gz

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tweet-api'
        publish-profile: ${{ secrets.AZURE_API }}
        startup-command: 'gunicorn --bind 0.0.0.0:$PORT --timeout 600 main:app'
