name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install spaCy model
      run: |
        python -m spacy download en_core_web_sm
    
    - name: Download model
      run: |
        curl -L -o model.zip https://raw.githubusercontent.com/Tristan-op/projet7-op/main/models/LSTM_plus_Lemmatization_plus_FastText_model.zip
        unzip model.zip -d ./models

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tweet-api'
        publish-profile: ${{ secrets.AZURE_API }}
        package: .

    - name: Run startup script
      run: |
        bash ./startup.sh
