name: main_tweet_api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Créer et activer un environnement virtuel
    - name: Create virtual environment
      run: |
        python -m venv .venv  # Créer un environnement virtuel appelé '.venv'
        source .venv/bin/activate

    - name: Install primary dependencies
      run: |
        source .venv/bin/activate  # Activer l'environnement virtuel
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: List installed packages
      run: |
        source .venv/bin/activate  # Activer l'environnement virtuel
        pip list  # Liste des packages pour vérifier si tout est bien installé

    - name: Download FastText model
      run: |
        source .venv/bin/activate  # Activer l'environnement virtuel
        wget -P ./modèle https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.fr.300.bin.gz
        gunzip ./modèle/cc.fr.300.bin.gz

    - name: Download LSTM model
      run: |
        source .venv/bin/activate  # Activer l'environnement virtuel
        wget -P ./modèle https://your-storage-server.com/models/sentiment_lstm_model.zip
        unzip ./modèle/sentiment_lstm_model.zip -d ./modèle

    - name: Run API
      run: |
        source .venv/bin/activate  # Activer l'environnement virtuel
        python main.py
