name: Deploy FastAPI app to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download FastText model
      run: |
        python -c "import fasttext.util; fasttext.util.download_model('en', if_exists='ignore')"
        mv cc.en.300.bin ./models/

    - name: Download and unzip machine learning model from GitHub
      run: |
        curl -L -o model.zip https://raw.githubusercontent.com/Tristan-op/projet7-op/main/models/LSTM_plus_Lemmatization_plus_FastText_model.zip
        unzip model.zip -d ./models/

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_API }}
        package: .
