name: main_tweet_api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 1 : Installer Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # Étape 2 : Créer et activer l'environnement virtuel
    - name: Create virtual environment
      run: |
        python -m venv .venv  # Créer un environnement virtuel appelé '.venv'
        source .venv/bin/activate  # Activer l'environnement virtuel
        python -m pip install --upgrade pip  # Mettre à jour pip

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        source .venv/bin/activate  # Activer l'environnement virtuel
        pip install --no-cache-dir -r requirements.txt  # Installer les dépendances listées dans requirements.txt

    # Étape 4 : Liste des packages installés pour vérifier si tout est bien installé
    - name: List installed packages
      run: |
        source .venv/bin/activate  # Activer l'environnement virtuel
        pip list  # Liste des packages installés

    # Étape 5 : Téléchargement du modèle FastText (si nécessaire)
    - name: Download FastText model
      run: |
        source .venv/bin/activate  # Activer l'environnement virtuel
        wget -P ./modèle https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.fr.300.bin.gz
        gunzip ./modèle/cc.fr.300.bin.gz

    # Étape 6 : Déployer sur Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tweet-api'
        publish-profile: ${{ secrets.AZURE_API }}
        
