name: Deploy FastAPI app to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # Créer et activer l'environnement virtuel, puis installer les dépendances via requirements.txt
    - name: Install dependencies from requirements.txt
      run: |
        python -m venv .venv  # Créer l'environnement virtuel
        . .venv/bin/activate  # Activer l'environnement virtuel
        python -m pip install --upgrade pip  # Mettre à jour pip
        pip install -r requirements.txt  # Installer les dépendances

    # Télécharger et décompresser le modèle de machine learning dans l'environnement virtuel
    - name: Download and unzip machine learning model
      run: |
        . .venv/bin/activate  # Activer l'environnement virtuel
        curl -L -o model.zip https://raw.githubusercontent.com/Tristan-op/projet7-op/main/models/LSTM_plus_Lemmatization_plus_FastText_model.zip
        unzip model.zip -d ./models/

    # Nettoyage avant déploiement pour libérer de l'espace disque
    - name: Final cleanup before deployment
      run: |
        rm -rf ~/.cache/pip
        rm -f model.zip
        rm -rf cc.en.300.bin.zip

    # Déployer sur Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_API }}
        package: .
