name: Deploy Flask API

on:
  push:
    branches:
      - main  # Déclencher le déploiement sur chaque push sur la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Make startup.sh executable
      run: chmod +x ./startup.sh  # Étape ajoutée pour rendre startup.sh exécutable

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tweet-api'
        publish-profile: ${{ secrets.AZURE_API }}
        package: .

    - name: Run startup.sh
      run: ./startup.sh


